#!/bin/bash
set -e
set -x
git push origin master
bundle exec nanoc compile
cd site
git pull origin master
cp -rv ../output/* .
git add *
git commit -m "Updating site through linenoise/portfolio"
git push origin master
cd ..
git commit site -m "Locking to latest release"
git push origin master
